### ISSUE TITLE
Images are loading slow

### ISSUE THREAD

**Issue by jamiehoward** [austin-rt/austin-rt.github.io#2]
Hey! Just checked out the portfolio site. One thing that I immediately noticed was that your images are loading slowly.

Looks like the filesizes are huge, so use an image optimizer or just Photoshop to bring those down to a much smaller size.

For example, https://austinrt.io/static/media/headshot-no-bg.bbf5d7a1509aeeab8e9e.png is over 9MB. It's only displayed about 400px wide on the site, but is a 2600px image.

Quick fixes that provide a big speed improvement! :)

**Comment by austin-rt** [comment]
Thank you so much! Good catch.

Just resolved this! https://github.com/austin-rt/austin-rt.github.io/commit/c8677c75d0e99e5924f9482ae136d4f43fced6af

**Comment by austin-rt** [comment]
Thank you so so much! Resolved.

https://github.com/austin-rt/austin-rt.github.io/commit/c8677c75d0e99e5924f9482ae136d4f43fced6af
